// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.Curiosity;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.PWMVictorSPX;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.SpeedControllerGroup;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainfrontLeft;
    public static SpeedController driveTrainbackLeft;
    public static SpeedControllerGroup driveTrainleftMotors;
    public static SpeedController driveTrainbackRight;
    public static SpeedController driveTrainfrontRight;
    public static SpeedControllerGroup driveTrainrightMotors;
    public static DifferentialDrive driveTrainrobotDrive;
    public static Encoder armLifterliftEncoder;
    public static SpeedController grippergripperMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainfrontLeft = new PWMVictorSPX(0);
        LiveWindow.addActuator("DriveTrain", "frontLeft", (PWMVictorSPX) driveTrainfrontLeft);
        driveTrainfrontLeft.setInverted(false);
        driveTrainbackLeft = new PWMVictorSPX(1);
        LiveWindow.addActuator("DriveTrain", "backLeft", (PWMVictorSPX) driveTrainbackLeft);
        driveTrainbackLeft.setInverted(false);
        driveTrainleftMotors = new SpeedControllerGroup(driveTrainfrontLeft, driveTrainbackLeft  );
        LiveWindow.addActuator("DriveTrain", "leftMotors", driveTrainleftMotors);
        
        driveTrainbackRight = new PWMVictorSPX(2);
        LiveWindow.addActuator("DriveTrain", "backRight", (PWMVictorSPX) driveTrainbackRight);
        driveTrainbackRight.setInverted(false);
        driveTrainfrontRight = new PWMVictorSPX(3);
        LiveWindow.addActuator("DriveTrain", "frontRight", (PWMVictorSPX) driveTrainfrontRight);
        driveTrainfrontRight.setInverted(false);
        driveTrainrightMotors = new SpeedControllerGroup(driveTrainbackRight, driveTrainfrontRight  );
        LiveWindow.addActuator("DriveTrain", "rightMotors", driveTrainrightMotors);
        
        driveTrainrobotDrive = new DifferentialDrive(driveTrainleftMotors, driveTrainrightMotors);
        LiveWindow.addActuator("DriveTrain", "robotDrive", driveTrainrobotDrive);
        driveTrainrobotDrive.setSafetyEnabled(false);
        driveTrainrobotDrive.setExpiration(0.1);
        driveTrainrobotDrive.setMaxOutput(1.0);

        armLifterliftEncoder = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("ArmLifter", "liftEncoder", armLifterliftEncoder);
        armLifterliftEncoder.setDistancePerPulse(1.0);
        armLifterliftEncoder.setPIDSourceType(PIDSourceType.kRate);
        grippergripperMotor = new VictorSP(4);
        LiveWindow.addActuator("Gripper", "gripperMotor", (VictorSP) grippergripperMotor);
        grippergripperMotor.setInverted(false);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
